trigger:
- master

jobs:

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: ./build.sh
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - bash: ./build.sh
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: .\build.ps1
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1